version: '3.3'

services:

  kafka_php_consumer:
    hostname: kafka_php_consumer
    container_name: kafka_php_consumer
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        PHP_IMAGE_TAG: 7.4-cli
    volumes:
      - ./:/app

  kafka_broker1:
    image: bitnami/kafka
    hostname: kafka_broker1
    container_name: kafka_broker1
    ports:
      - '9093:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafka_zookeeper

  kafka_broker2:
    image: bitnami/kafka
    hostname: kafka_broker2
    container_name: kafka_broker2
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafka_zookeeper

  kafka_zookeeper:
    image: zookeeper
    hostname: kafka_zookeeper
    container_name: kafka_zookeeper
    ports:
      - "2181:2181"
      - "9091:8080"