version: '3.3'

services:

  kafka_php_consumer:
    hostname: kafka_php_consumer
    container_name: kafka_php_consumer
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        PHP_IMAGE_TAG: 7.4-cli
    volumes:
      - ./:/app
    entrypoint: ["php", "/app/bin/app.php consumePartition"]

  kafka_php_producer:
    hostname: kafka_php_producer
    container_name: kafka_php_producer
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        PHP_IMAGE_TAG: 7.4-cli
    volumes:
      - ./:/app
    entrypoint: ["php", "/app/bin/app.php produce"]

  kafka_broker1:
    image: bitnami/kafka
    hostname: kafka_broker1
    container_name: kafka_broker1
    ports:
      - '9093:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafka_zookeeper

  kafka_broker2:
    image: bitnami/kafka
    hostname: kafka_broker2
    container_name: kafka_broker2
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafka_zookeeper

  kafka_broker3:
    image: bitnami/kafka
    hostname: kafka_broker3
    container_name: kafka_broker3
    ports:
      - '9095:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafka_zookeeper

  kafka_zookeeper:
    image: zookeeper
    hostname: kafka_zookeeper
    container_name: kafka_zookeeper
    ports:
      - "2181:2181"
      - "9091:8080"

  kafka_zookeeper_ui:
    image: elkozmon/zoonavigator:latest
    hostname: kafka_zookeeper_ui
    container_name: kafka_zookeeper_ui
    ports:
      - '9090:9090'
    environment:
      - HTTP_PORT=9090
      - AUTO_CONNECT_CONNECTION_STRING=kafka_zookeeper