version: '3.3'

services:

  kafka_php_consumer:
    hostname: kafka_php_consumer
    container_name: kafka_php_consumer
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        PHP_IMAGE_TAG: 7.4-cli
    image: kafkalabs_php_consumer
    volumes:
      - ./:/app
    entrypoint: ["php", "/app/bin/app.php consumePartition"]
    depends_on:
      - kafkalabs_broker1
      - kafkalabs_broker2
      - kafkalabs_broker3

  kafkalabs_php_producer:
    hostname: kafkalabs_php_producer
    container_name: kafkalabs_php_producer
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        PHP_IMAGE_TAG: 7.4-cli
    image: kafkalabs_php_producer
    volumes:
      - ./:/app
    entrypoint: ["php", "/app/bin/app.php produce"]
    depends_on:
      - kafkalabs_broker1
      - kafkalabs_broker2
      - kafkalabs_broker3

  kafkalabs_broker1:
    image: bitnami/kafka
    hostname: kafkalabs_broker1
    container_name: kafkalabs_broker1
    ports:
      - '9093:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafkalabs_zookeeper

  kafkalabs_broker2:
    image: bitnami/kafka
    hostname: kafkalabs_broker2
    container_name: kafkalabs_broker2
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafkalabs_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafkalabs_zookeeper

  kafkalabs_broker3:
    image: bitnami/kafka
    hostname: kafkalabs_broker3
    container_name: kafkalabs_broker3
    ports:
      - '9095:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafkalabs_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafkalabs_zookeeper

  kafkalabs_zookeeper:
    image: zookeeper
    hostname: kafkalabs_zookeeper
    container_name: kafkalabs_zookeeper
    ports:
      - "2181:2181"
      - "9091:8080"

  kafkalabs_zookeeper_ui:
    image: elkozmon/zoonavigator:latest
    hostname: kafkalabs_zookeeper_ui
    container_name: kafkalabs_zookeeper_ui
    ports:
      - '9090:9090'
    environment:
      - HTTP_PORT=9090
      - AUTO_CONNECT_CONNECTION_STRING=kafkalabs_zookeeper